name: Visual Regression Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: regviz/node-xcb

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: v1-dependencies-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          v1-dependencies-${{ hashFiles('package.json') }}-
          v1-dependencies-

    - name: Install dependencies
      run: npm install

    - name: Check lint
      run: npm run lint

    - name: Build Storybook
      run: npm run build-storybook

    - name: Capture screenshots
      run: npm run screenshot

    # - name: Run regression
    #   run: npm run regression
env:
  REG_NOTICE_CLIENT_ID: M7MwNzKxNDWw1C/LLC5NzIkvSS0u0TcxNDE1MTc21y/IzytJNDQAAA==
